# Generated by Django 3.2.9 on 2021-11-29 17:54

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('token', models.TextField(primary_key=True, unique=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=models.deletion.DO_NOTHING,
                        to='api.User',
                    ),
                ),
                ('expired_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
